DROP TABLE IF EXISTS aluno;
CREATE TABLE aluno (
	`id` INT NOT NULL AUTO_INCREMENT,
	`nome` VARCHAR(50) NOT NULL,
	`nota1` FLOAT NOT NULL,
	`nota2` FLOAT NOT NULL,
	`nota3` FLOAT NOT NULL,
	`nota4` FLOAT NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


INSERT INTO aluno VALUES (NULL, 'Carolina', 10.0, 9.6, 7.2, 8.8);
INSERT INTO aluno VALUES (NULL, 'Manuel',  9.0, 4.6, 3.2, 2.8);
INSERT INTO aluno VALUES (NULL, 'Bruna',  3.5, 5.76, 8.2, 7.8);
